version: 2.1

orbs:
  trivy: gotooooo/trivy@<< pipeline.parameters.dev-orb-version >>
  orb-tools: circleci/orb-tools@10.0.3

parameters:
  run-integration-tests:
    description: An internal flag to prevent integration test from running before a development version has been created.
    type: boolean
    default: false
  dev-orb-version:
    description: >
      The development version of the orb to test.
      This value is automatically adjusted by the "trigger-integration-tests-workflow" job to correspond with the specific version created by the commit and should not be edited.
      A "dev:alpha" version must exist for the initial pipeline run.
    type: string
    default: "dev:alpha"

jobs:
  integration-test:
    executor: orb-tools/ubuntu
    steps:
      - checkout

# jobs:
#   build:
#     docker:
#       - image: circleci/python:latest
#     steps:
#       - setup_remote_docker
#       - run:
#           name: set image
#           command: |
#             export NAME="nginx:latest"
#             echo "export NAME=${NAME}" >> $BASH_ENV
#       - trivy/scan_an_image:
#           image: $NAME
#           severity: HIGH,CRITICAL
#           exit-code: 1
#           no-progress: true

workflows:
  version: 2
  test-pack:
    jobs:
      - orb-tools/lint
      - orb-tools/pack
      - orb-tools/publish-dev:
          orb-name: gotooooo/trivy
          context: circleci-orb-publishing
          requires:
            - orb-tools/lint
            - orb-tools/pack
      - orb-tools/trigger-integration-tests-workflow:
          name: trigger-integration-dev
          context: circleci-orb-publishing
          requires:
            - orb-tools/publish-dev
    unless: << pipeline.parameters.run-integration-tests >>
