version: 2.1

orbs:
  trivy: gotooooo/trivy@dev:58952a3

jobs:
  build:
    docker:
      - image: circleci/python:latest
    steps:
      - setup_remote_docker
      - run:
          name: set image
          command: |
            export NAME="nginx:latest"
            echo "export NAME=${NAME}" >> $BASH_ENV
      - trivy/scan_an_image:
          image: $NAME
          severity: HIGH,CRITICAL
          exit-code: 1
          no-progress: true

workflows:
  version: 2
  workflow:
    jobs:
      - build

